import sys

def main():
  n = 9
  init_str = ""
  for i in range(1,n+1):
    init_str += str(i)
  print init_str  
  ret = permute(init_str, n)
  ret.sort()
  print "Number of permutations: ", len(ret)

  pandigital(ret)

def pandigital(perms):
  res = 0 # sum of all products generated by pandigital multiplicand/multiplier/product
  list_of_pan_prod = []
  for key in perms:
    if list_of_pan_prod.count(key[5:]) == 0:
      if int(key[:1])*int(key[1:5]) == int(key[5:]):
        res += int(key[5:])
        list_of_pan_prod.append(key[5:])
      elif int(key[:2])*int(key[2:5]) == int(key[5:]):
        res += int(key[5:])        
        list_of_pan_prod.append(key[5:])
  print "SUM: ",res
  print "list of pandigital products:", list_of_pan_prod

def permute(init_str,n):
  perm_list = []
  if n == 1:
    perm_list.append(init_str)
    return perm_list
  ret_list = permute(init_str[1:],n-1)
  for key in ret_list:
    for j in range(0,n):
      perm_list.append(key[:j] + init_str[0] + key[j:])
  return perm_list

if __name__ == "__main__":
  main()
